stages:
  - check-cluster
  - build
  - push

check-kube:
  stage: check-cluster
  image: 
    name: bitnami/kubectl:1.24
    entrypoint: ['']
  tags: 
    - xor
  script:
    - kubectl config get-contexts
    - kubectl config use-context owi-learning/kubeconfig:xor
    - kubectl get pods

build-docker-job:
  tags:
    - xor
  stage: build
  script:
    - docker build -t reg.k8s.icydusk.io/amazing-games-backend:latest -t reg.k8s.icydusk.io/amazing-games-backend:$CI_COMMIT_SHA .

publish-image:
  tags:
    - xor
  stage: push
  script:
    - docker push reg.k8s.icydusk.io/amazing-games-backend --all-tags

