stages:
  - build
  - push

build-docker-job:
  stage: build
  script:
    - docker build -t reg.k8s.icydusk.io/amazing-games-backend:latest -t reg.k8s.icydusk.io/amazing-games-backend:${CI_COMMIT_TAG} .

publish-image:
  stage: push
  script:
    - docker push reg.k8s.icydusk.io/amazing-games-backend --all-tags

