stages:
  - check-cluster
  - build
  - push

check-kube:
  image: bitnami/kubectl:latest
  tags: 
    - xor
  stage: check-cluster
  script:
    - kubectl config get-contexts

build-docker-job:
  tags:
    - xor
  stage: build
  script:
    - docker build -t reg.k8s.icydusk.io/amazing-games-backend:latest -t reg.k8s.icydusk.io/amazing-games-backend:$CI_COMMIT_SHA .

publish-image:
  tags:
    - xor
  stage: push
  script:
    - docker push reg.k8s.icydusk.io/amazing-games-backend --all-tags

